version: '3.9'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: segretodistato
        volumes:
            - ./db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8888:80
        environment:
            PGADMIN_DEFAULT_EMAIL: folders@fold.com
            PGADMIN_DEFAULT_PASSWORD: segreto
        volumes:
            - ./servers.json:/pgadmin4/servers.json
            - ./passwordfile:/passwordfile
